export enum GeneralState {
  NOT_SPECIFIED = 'NOT_SPECIFIED',
  NORMAL = 'NORMAL',
  SATISFYING = 'SATISFYING',
  SLUGGISH = 'SLUGGISH',
  MODERATE_SEVERITY = 'MODERATE_SEVERITY',
  SERIOUS_СONDITION = 'SERIOUS_СONDITION',
  EXTREMELY_SERIOUS_СONDITION = 'EXTREMELY_SERIOUS_СONDITION',
  AGONY = 'AGONY',
}
