export enum BaseToken {
  GLOBAL_DB_CONTEXT = 'GLOBAL_DB_CONTEXT',
  GLOBAL_READ_DB_CONTEXT = 'GLOBAL_READ_DB_CONTEXT',
  IDENTITY_CONTEXT = 'IDENTITY_CONTEXT',
  DATA_SOURCE = 'DATA_SOURCE',
}

export enum QueryToken {
  LIST_CLIENTS = 'LIST_CLIENTS',
  GET_CLIENT = 'GET_CLIENT',
  LIST_PETS_BY_CLIENT = 'LIST_PETS_BY_CLIENT',
  LIST_APPOINTMENTS_BY_CLIENT = 'LIST_APPOINTMENTS_BY_CLIENT',

  LIST_PETS = 'LIST_PETS',
  GET_PET = 'GET_PET',
  LIST_APPOINTMENTS_BY_PET = 'LIST_APPOINTMENTS_BY_PET',

  LIST_APPOINTMENTS = 'LIST_APPOINTMENTS',
  GET_APPOINTMENT = 'GET_APPOINTMENT',

  LIST_EVENTS = 'LIST_EVENTS',
}

export enum CommandToken {}

export enum DomainServiceToken {}

export enum ServiceToken {
  EMAIL_SENDER = 'EMAIL_SENDER',
  AUTH_SERVICE = 'AUTH_SERVICE',
}

export enum ProviderToken {}
